
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint
concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "develop" ]
  schedule:
    - cron: '30 7 * * 1'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          cd App
          npm install eslint@8.10.0 --legacy-peer-deps
          npm install @microsoft/eslint-formatter-sarif@2.1.7 --legacy-peer-deps
      - name: Run ESLint
        run: |
          cd App
          npx eslint . --config .eslintrc.js --ext .js,.jsx,.ts,.tsx
        continue-on-error: false